site_name: "eucalypt"
repo_url: https://github.com/curvelogic/eucalypt
copyright: "Copyright (C) 2018-2026 Greg Hawkins"
docs_dir: docs
nav:
- Home: index.md
- Getting Started: getting-started.md
- Syntax: syntax.md
- Syntax Gotchas: syntax-gotchas.md
- Operators and Identifiers: operators-and-identifiers.md
- Anaphora and Lambdas: anaphora-and-lambdas.md
- Command Line: command-line.md
- Imports: imports.md
- YAML Embedding: yaml-embedding.md
- Prelude Reference: prelude.md
- Testing: tester.md
- Implementation:
  - Overview: implementation.md
  - Architecture: architecture.md
  - GC Implementation: gc-implementation.md
  - GC Benchmarking: gc-benchmarking.md
- Philosophy: philosophy-lang.md
markdown_extensions:
  - admonition
  - footnotes
  - tables
theme: readthedocs
